### ISSUE TITLE
stream underflow(update dependencies)

### ISSUE THREAD

**Issue by AlainCx** [tomoyanonymous/rtpsendreceive#3]
Hello,
I'm trying to use rtpsendreceive with Max 8 but I've got errors in the console : "stream underflow detected !"
I've no sound back in the rtpreceive with the loop patch test.
I'm using Max 8.5.2 and Windows 10.

Any help would be appreciated

**Comment by tomoyanonymous** [comment]
Hi. The message just means audio processing didn't finished within the buffer polling.

I tested on Max `self_loop_test.maxpat` on Max v8.5.0, macOS 12.3.1 and got errors too.
The project hasn't been built for years, maybe something has been changed in Max API at v8.5.

I'll try to upgrade dependencies but I do not have enough time to concentrate this project due to my main job.  
So if you (or someone) can help, please send me PR.

**Comment by AlainCx** [comment]
Thanks for your answer.

**Comment by AlainCx** [comment]
I had made some tests with NDI and it suits my need : stream from Max on local network and record with OBS.
I use this external :
https://github.com/pixsper/jit.ndi

**Comment by tomoyanonymous** [comment]
yeah this project was a little bit before jit.ndi & NDI 5.0 came. It would be more stable than this dirty project now.
Anyway, as long as I tried, the problem should happen when the signal vector size was too smaller than IO vector size. By setting the 2 vector sizes the same, the error disappeared and could send the audio.
I'll add the notes on readme!

**Comment by AlainCx** [comment]
understood.
Thanks
